### ISSUE TITLE
Information for the 'Integrated Pathway' buttons

### ISSUE THREAD

**Issue by HauHe** [ReeemProject/reeempathways#67]
Dear @olavurellefsen, dear @MFHolm ,
When going to the buttons for the integrated pathways one doesn't know what they actually stand for. Would it be possible to have a small pop up when one remains with the cursor over the button with the two phrase description that is under pathways and a disclaimer that more information can be found under pathways?
This would be good for all three pathways but also for 'Model', 'Reference', and 'Paris Agreement EU'. For those three I actually don't see any description.
Sorry for the trouble!

**Comment by olavurellefsen** [comment]
Fixed in #81. Regarding the three secondary pathways (model, reference, and paris agreement eu), they have been disabled in the interface for now.
