### ISSUE TITLE
Overlap of Unit and numbers on axis

### ISSUE THREAD

**Issue by HauHe** [ReeemProject/reeempathways#72]
Dear @olavurellefsen , dear @MFHolm , dear @HelenaEgholm ,

in several graphs, specifically where the axis labeling numbers are large, the numbers and units of the y-axis overlap. 
Would it be possible to change the layout? Or to change the numbers for example to in thousands?

/Hauke

**Comment by olavurellefsen** [comment]
Fixed with #85
