### ISSUE TITLE
Text on start page

### ISSUE THREAD

**Issue by HauHe** [ReeemProject/reeempathways#73]
Dear @olavurellefsen , @HelenaEgholm , dear @FraGard, 
the text on the start page seems to be in parts from the REEEM impact report. I'm wondering if the sections mentioned in the second half of the text are somehow relating to the pathways tool?
If not I would suggest to revise the text. Francesco Gardumi is also on GitHub as FraGard.

/Hauke

**Comment by olavurellefsen** [comment]
Resolved with #79 - thanks :-)
